Meta t notebook updates fall24
biocore/metagenomics_pooling_notebook pull request #262
Opened 2024-12-09 22:20 UTC by RodolfoSalido

Mostly jupyter notebook template work. 

Need to write unit tests for an updated format_echo_pooling_picklist() function.

2025-01-03 20:08 UTC, RodolfoSalido commented
should resolve #242

2025-01-06 18:53 UTC, AmandaBirmingham approved these changes
Thank you, Rodolfo!

2025-01-10 05:37 UTC, charles-cowart requested changes
Most things appear in order. Just a few questions I'd like confirmations on before approving. Thanks!

2025-01-10 05:37 UTC, charles-cowart commented on notebooks/test_data/Quant/MiniPico/2024_NPH_Plates_3-5_gDNA_quant.txt
This file and others like it appear to be modified binary files in the GitHub UI, but they are not present if the branch is downloaded and reviewed. My interpretation of this is that the files are 'Unicode text, UTF-16, little-endian text, with CRLF line terminators', as are many of the current files in this folder are, and the UI is interpreting them as binary files.

2025-01-10 05:37 UTC, charles-cowart commented on notebooks/test_data/Quant/MiniPico/2024_NPH_Plates_3-5_gDNA_quant.txt
@RodolfoSalido can you please confirm that 2024_NPH_Plates_3-5_gDNA_quant.txt and similarly named files were deleted? If so then no further investigation is needed and no additional actions need to be taken.

2025-01-10 05:37 UTC, charles-cowart commented on notebooks/test_data/Quant/MiniPico/2024_NPH_Plates_7-10_Post_DNase_DNA_Quant.txt
@RodolfoSalido @AmandaBirmingham Just to be clear, these 'txt' files are in UTF-16 format (specifically Unicode text, UTF-16, little-endian text, with CRLF line terminators as per 'file' command). MacOS and Windows are able to open these files if you double-click on them in a UI but from the console they can appear as 'binary garbage' from a Linux or MacOS terminal window. My guess is these are generated on Windows or something like the iSeq 100 sequencer that's built on top of Windows, since it's the only platform I know of that uses UTF-16 natively. Just to confirm, we're cool with  retaining this format going into the future, right? It's not a hassle on my end but my guess is it could be confusing for grad students who aren't familiar with such things.

2025-01-10 17:35 UTC, RodolfoSalido commented on notebooks/test_data/Quant/MiniPico/2024_NPH_Plates_7-10_Post_DNase_DNA_Quant.txt
these files are direct outputs from our plate reader (SpectraMax i3x) on a Windows PC.

2025-01-10 17:43 UTC, RodolfoSalido commented on notebooks/test_data/Quant/MiniPico/2024_NPH_Plates_3-5_gDNA_quant.txt
That is correct, they were deleted and replaced with alternative test_data (NPH_7_10). The new test data allowed for the use of matrix tube sample accession workflow.

2025-01-10 20:18 UTC, RodolfoSalido commented on metapool/metapool.py
> +                                   ]]
Added an error message that checks for the columns and suggests the most likely root cause of error. Also added required columns in the docstring.

2025-01-10 20:19 UTC, RodolfoSalido commented on metapool/metapool.py
> +        # # ################################################ # #
was trying to denote the block of code that is legacy, but I'll get rid of them.

2025-01-10 20:23 UTC, RodolfoSalido commented
made requested changes

2025-01-10 20:38 UTC, charles-cowart approved these changes
Approved! Ty Rodolfo!

2025-01-10 20:38 UTC, merged