Fix negative plate reader concentration handling
biocore/metagenomics_pooling_notebook pull request #58
Opened 2021-12-06 23:16 UTC by RodolfoSalido

Fixed read_pico_csv() to limit concentration range to (0 , 60)

2021-12-06 23:41 UTC, antgonza commented
Hey @RodolfoSalido, you need to solve conflicts for this to move forward. If you do `git pull https://github.com/biocore/metagenomics_pooling_notebook master` it should download the latests version of master and show you the conflicts so you can fix them.

2021-12-06 23:50 UTC, RodolfoSalido commented
I think I resolved the conflict?

2021-12-06 23:53 UTC, antgonza commented
Yup, but now there are flake8 errors, just add a space after each `,`

2021-12-12 00:28 UTC, ElDeveloper requested changes

2021-12-12 00:28 UTC, ElDeveloper commented on metapool/metapool.py
> +    pico_df[conc_col_name] = np.clip(pico_df[conc_col_name], 0, 60)
I thought this should only be done for `SpectraMax_i3x` if so can you add something like: `if plate_reader == 'SpectraMax_i3x': ....`

2021-12-12 00:28 UTC, ElDeveloper commented
@RodolfoSalido also, can you add a test for these changes?

2022-01-13 19:29 UTC, antgonza reviewed
I thought that this PR will have conflicts after merging https://github.com/biocore/metagenomics_pooling_notebook/pull/62 but it seem fine; which is surprising but kind of cool. Anyway, one comment; thank you.

2022-01-13 19:29 UTC, antgonza commented on metapool/tests/test_metapool.py
> +                                     'pico_spectramax.txt')
Thank you @RodolfoSalido; what do you think about adding a small test to make sure that there are actually values out of the range in fp_spectramax? I tried to find them but it was a bit complicated for me.

2022-01-13 19:32 UTC, RodolfoSalido commented
I can add that test. 

-Rodolfo

Sent from my iPhone

> On Jan 13, 2022, at 11:29 AM, Antonio Gonzalez ***@***.***> wrote:
> 
> ﻿
> @antgonza commented on this pull request.
> 
> I thought that this PR will have conflicts after merging #62 but it seem fine; which is surprising but kind of cool. Anyway, one comment; thank you.
> 
> In metapool/tests/test_metapool.py:
> 
> > @@ -190,6 +190,18 @@ def test_read_pico_csv_spectramax(self):
>          with self.assertRaises(ValueError):
>              read_pico_csv(fp_spectramax, plate_reader='foo')
>  
> +    def test_read_pico_csv_spectramax_negfix(self):
> +        # Tests that Concentration values are clipped
> +        # to a range of (0,60), eliminating possible
> +        # negative concentration values.
> +        fp_spectramax = os.path.join(os.path.dirname(__file__), 'data',
> +                                     'pico_spectramax.txt')
> Thank you @RodolfoSalido; what do you think about adding a small test to make sure that there are actually values out of the range in fp_spectramax? I tried to find them but it was a bit complicated for me.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you were mentioned.

2022-03-24 19:04 UTC, RodolfoSalido commented
can we merge this ? Need someone to approve my new pico_spectramax.txt file.

2022-03-24 19:24 UTC, antgonza commented
Just to be clear, you need to solve the conflicts via CLI in your local version; please email me if you need help with this.

2022-04-13 18:11 UTC, RodolfoSalido commented
Not super sure what the new errors are. I managed to fix the issue with the conflict by merging my local branch with the upstream biocore, but now I'm getting new(different) errors.

2022-04-13 19:18 UTC, RodolfoSalido commented
Ok, after many small edits, I think I got my local branch to have no conflicts with the base branch, and pass all tests. But I'm getting a check error that I'm not familiar with. Any help?

2022-04-14 13:21 UTC, antgonza commented
Thank you @RodolfoSalido; I think the failure was a github actions hiccup that has been solved - I restarted the tests and now are passing.

2022-04-14 13:21 UTC, merged